version: '3'

services:
  dbpostgresql:
    image: "postgres"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped
  app:
    build: .
    image: app
    container_name: app
    ports:
      - "8080:8080"
#    environment:
 #     SPRING_DATASOURCE_URL: jdbc:postgresql://testdb
#      SPRING_DATASOURCE_USERNAME: admin
#      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - dbpostgresql

